name: Build and Release tab-keeper-react-chrome-extension

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Get version from manifest
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'public/manifest.json'
          prop_path: 'version'

      - name: Install zip dependency
        run: npm install --save-dev bestzip

      - name: Run release script
        run: npm run release

      - name: Move zip to known location
        run: mv *.zip tab-keeper-react-chrome-extension-v${{steps.version.outputs.prop}}.zip

      - name: Upload original zip file ready for Chrome Web Store
        uses: actions/upload-artifact@v3
        with:
          path: tab-keeper-react-chrome-extension-v${{steps.version.outputs.prop}}.zip
